//! The card-kind registry (P1.3, audit finding K3).
//!
//! `cards.kind` is no longer guarded by a SQL `CHECK` (migration 0021): the
//! set of kinds lives here, in [`CardKind`], and everything a kind needs on
//! the backend — its board projection, single-card load, subtree copy, hard
//! delete, search rows, asset ownership and journal codec — is one
//! [`CardKindHandler`] impl in `domain::kinds`. The generic code
//! (`load_cards`, `load_card`, `duplicate_board`, `empty_trash`,
//! `search_workspace`, `collect_orphaned_assets`) iterates [`registry`]
//! instead of matching on kind strings.
//!
//! Adding a kind = a variant here + one handler file + one registry entry +
//! one migration creating its detail table. No `cards` rebuild, and no
//! `kind IN ('…')` literal anywhere else: SQL lists are generated by
//! [`sql_in_list`].

use std::fmt;
use std::str::FromStr;

use rusqlite::{Connection, Transaction};

use crate::domain::errors::WorkspaceError;
use crate::domain::models::{AssetDto, CardDto};

pub use crate::domain::kinds::{handler, registry};

/// Every card kind the backend knows. The declaration order is the registry
/// order and therefore the order in which a board snapshot lists its cards.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CardKind {
    Note,
    BoardPortal,
    Image,
    Embed,
    FilesystemAlias,
    File,
    BoardShortcut,
}

impl CardKind {
    /// Every kind, in registry order.
    pub const ALL: &'static [CardKind] = &[
        CardKind::Note,
        CardKind::BoardPortal,
        CardKind::Image,
        CardKind::Embed,
        CardKind::FilesystemAlias,
        CardKind::File,
        CardKind::BoardShortcut,
    ];

    /// Leaf kinds: everything that is not a board's primary portal. Leaf
    /// cards can be trashed, moved between boards and placed out of Unsorted
    /// on their own; a portal only ever moves/trashes with its board.
    pub const LEAF: &'static [CardKind] = &[
        CardKind::Note,
        CardKind::Image,
        CardKind::Embed,
        CardKind::FilesystemAlias,
        CardKind::File,
        CardKind::BoardShortcut,
    ];

    /// The value stored in `cards.kind` (and the DTO's serde tag).
    pub const fn as_str(self) -> &'static str {
        match self {
            CardKind::Note => "note",
            CardKind::BoardPortal => "board_portal",
            CardKind::Image => "image",
            CardKind::Embed => "embed",
            CardKind::FilesystemAlias => "filesystem_alias",
            CardKind::File => "file",
            CardKind::BoardShortcut => "board_shortcut",
        }
    }

    /// Rust-side replacement for the dropped `CHECK(kind IN (…))`.
    pub fn is_valid(kind: &str) -> bool {
        kind.parse::<CardKind>().is_ok()
    }
}

impl fmt::Display for CardKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl FromStr for CardKind {
    type Err = WorkspaceError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        CardKind::ALL
            .iter()
            .copied()
            .find(|kind| kind.as_str() == s)
            .ok_or_else(|| WorkspaceError::ConstraintViolation(format!("unknown card kind: {s}")))
    }
}

/// `('note', 'image', …)` for a SQL `kind IN …` clause. Kind names are
/// compile-time constants, so inlining them is injection-safe.
pub fn sql_in_list(kinds: &[CardKind]) -> String {
    let quoted: Vec<String> = kinds
        .iter()
        .map(|kind| format!("'{}'", kind.as_str()))
        .collect();
    format!("({})", quoted.join(", "))
}

/// What a handler needs to copy one card's detail row while duplicating a
/// board subtree (`duplicate_board`). Only the portal handler uses most of
/// it: a nested portal recursively duplicates its own target board under
/// `new_board_id` and points the copied portal at that fresh board.
pub struct CopyContext<'a> {
    pub workspace_id: &'a str,
    /// The freshly-created board the copied card now belongs to.
    pub new_board_id: &'a str,
    pub now: i64,
    /// Nesting depth of `new_board_id` in the duplicate (1 = the root copy).
    pub depth: u32,
}

/// One search hit before board identities are attached. `rank` orders
/// results (0 = title-level match, before body matches); see
/// `repositories::search::search_workspace`.
#[derive(Debug, Clone)]
pub struct SearchHit {
    pub entity_id: String,
    /// The search-result kind shown to the UI (`note`, `image`, `link`, …).
    pub kind: &'static str,
    pub title: String,
    pub excerpt: Option<String>,
    pub board_id: String,
    pub rank: i64,
    pub thumbnail_asset: Option<AssetDto>,
    pub created_at: i64,
}

/// One full-text candidate for a card of a given kind: the card id and
/// whether the query matched the card's title-level text (the `title` column
/// of `search_index`, migration 0022). Candidates are already restricted to
/// live cards on live boards.
#[derive(Debug, Clone)]
pub struct SearchCandidate {
    pub entity_id: String,
    pub title_hit: bool,
}

/// Everything the backend does per card kind. One impl per kind in
/// `domain::kinds`, registered in [`registry`].
pub trait CardKindHandler: Sync + Send {
    fn kind(&self) -> CardKind;

    /// Active cards of this kind on `board_id`: the canvas (`unsorted =
    /// false`) or the Unsorted panel (`unsorted = true`), ordered by
    /// `(z_index, id)`. Portals carry live subtree counts on the canvas only.
    fn load_many(
        &self,
        conn: &Connection,
        board_id: &str,
        unsorted: bool,
    ) -> Result<Vec<CardDto>, WorkspaceError>;

    /// One active card of this kind, or `None` when there is no such live
    /// card (or its detail row is missing).
    fn load_one(&self, conn: &Connection, id: &str) -> Result<Option<CardDto>, WorkspaceError>;

    /// Copies the detail row of `from_id` onto the already-inserted `cards`
    /// row `to_id` (board duplication).
    fn copy_detail(
        &self,
        tx: &Transaction,
        from_id: &str,
        to_id: &str,
        ctx: &CopyContext,
    ) -> Result<(), WorkspaceError>;

    /// Hard-deletes this kind's detail rows for `ids` (empty trash). Returns
    /// the number of rows removed. Must not touch `cards` itself.
    fn delete_details(&self, tx: &Transaction, ids: &[String]) -> Result<u64, WorkspaceError>;

    /// Loads the hits for `candidates` — cards of this kind that the
    /// full-text index matched for `query` (already trimmed, non-empty) —
    /// with their display title, excerpt and rank. Matching happens in
    /// `repositories::search`; this only projects. Order is irrelevant (the
    /// caller ranks). Kinds with nothing searchable return an empty list.
    fn search_rows(
        &self,
        conn: &Connection,
        query: &str,
        candidates: &[SearchCandidate],
    ) -> Result<Vec<SearchHit>, WorkspaceError>;

    /// `(detail table, column)` pairs whose value is an `assets.id` this kind
    /// owns. Asset GC keeps an asset alive while any of these references it.
    fn asset_refs(&self) -> &'static [(&'static str, &'static str)];

    /// The detail row as JSON (journal codec, ADR-0011). Lossless: feeding it
    /// back through [`CardKindHandler::from_payload`] restores the same row.
    fn to_payload(&self, conn: &Connection, id: &str) -> Result<serde_json::Value, WorkspaceError>;

    /// Writes (inserts or replaces) the detail row of card `id` from a payload
    /// produced by [`CardKindHandler::to_payload`]. The `cards` row must exist.
    // The journal-codec name pairs with `to_payload` (ADR-0011); it decodes
    // into the database, not into `Self`.
    #[allow(clippy::wrong_self_convention)]
    fn from_payload(
        &self,
        tx: &Transaction,
        id: &str,
        payload: &serde_json::Value,
    ) -> Result<(), WorkspaceError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_every_kind_name() {
        for kind in CardKind::ALL {
            assert_eq!(kind.as_str().parse::<CardKind>().unwrap(), *kind);
        }
        assert!(matches!(
            "test_kind".parse::<CardKind>(),
            Err(WorkspaceError::ConstraintViolation(_))
        ));
        assert!(!CardKind::is_valid("test_kind"));
    }

    #[test]
    fn leaf_is_all_but_portal() {
        let expected: Vec<CardKind> = CardKind::ALL
            .iter()
            .copied()
            .filter(|k| *k != CardKind::BoardPortal)
            .collect();
        assert_eq!(CardKind::LEAF, expected.as_slice());
    }

    #[test]
    fn builds_a_sql_list() {
        assert_eq!(
            sql_in_list(&[CardKind::Note, CardKind::Image]),
            "('note', 'image')"
        );
    }
}
